apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: php-devopproj
        imagePullPolicy: Never   # 👈 This tells K8s to NOT pull from Docker Hub
        ports:
        - containerPort: 80
